"""Tests for syslog-ng config generator (generators/syslog.py)."""

from __future__ import annotations

import subprocess
from unittest.mock import MagicMock, patch

from conftest import make_device

from netbox2prom.generators.syslog import (
    _build_content,
    _check_syntax,
    _remove_safely,
    _run_ctl,
    _validate_structure,
    generate_syslog_config,
    reload_syslog,
)

# ---------------------------------------------------------------------------
# _validate_structure
# ---------------------------------------------------------------------------


class TestValidateStructure:
    def test_valid_block(self) -> None:
        content = '# comment\nrewrite fix_hostnames {\n  set("rtr1" value(".Host"));\n};\n'
        valid, error = _validate_structure(content, "fix_hostnames")
        assert valid is True
        assert error == ""

    def test_missing_opening(self) -> None:
        valid, error = _validate_structure("some text\n};\n", "fix_hostnames")
        assert valid is False
        assert "Expected block to start" in error

    def test_missing_closing(self) -> None:
        valid, error = _validate_structure("rewrite fix_hostnames {\n", "fix_hostnames")
        assert valid is False
        assert "end with" in error

    def test_unbalanced_braces(self) -> None:
        content = "rewrite fix_hostnames {\n{\n};\n"
        valid, error = _validate_structure(content, "fix_hostnames")
        assert valid is False
        assert "Unbalanced" in error

    def test_unmatched_closing_brace(self) -> None:
        content = "rewrite fix_hostnames {\n}\n}\n};\n"
        valid, error = _validate_structure(content, "fix_hostnames")
        assert valid is False
        assert "Unmatched closing brace" in error

    def test_braces_inside_strings_ignored(self) -> None:
        content = 'rewrite fix_hostnames {\n  set("hello}world" value(".Test"));\n};\n'
        valid, error = _validate_structure(content, "fix_hostnames")
        assert valid is True

    def test_escaped_quotes_in_strings(self) -> None:
        content = 'rewrite fix_hostnames {\n  set("say \\"hello\\"" value(".Test"));\n};\n'
        valid, error = _validate_structure(content, "fix_hostnames")
        assert valid is True

    def test_comments_skipped(self) -> None:
        content = "# comment with } brace\nrewrite fix_hostnames {\n  rule;\n};\n"
        valid, error = _validate_structure(content, "fix_hostnames")
        assert valid is True


# ---------------------------------------------------------------------------
# _build_content
# ---------------------------------------------------------------------------


class TestBuildContent:
    def test_basic_content(self) -> None:
        content = _build_content("fix_hostnames", ["rule1;", "rule2;"], "")
        assert content.startswith("# Generated by netbox2prom")
        assert "rewrite fix_hostnames {" in content
        assert "rule1;" in content
        assert "rule2;" in content
        assert content.rstrip().endswith("};")

    def test_with_epilogue(self) -> None:
        content = _build_content("test_block", ["rule1;"], "extra_config;")
        assert "extra_config;" in content
        assert content.rstrip().endswith("};")

    def test_empty_rules(self) -> None:
        content = _build_content("test_block", [], "")
        assert "rewrite test_block {" in content
        assert content.rstrip().endswith("};")


# ---------------------------------------------------------------------------
# generate_syslog_config
# ---------------------------------------------------------------------------


class TestGenerateSyslogConfig:
    def test_no_config_file_returns_false(self) -> None:
        result = generate_syslog_config([], {"groups": {}})
        assert result is False

    def test_no_matching_devices_no_existing_file(self, tmp_path) -> None:
        cfg = {
            "config_file": str(tmp_path / "syslog.conf"),
            "block_name": "fix_hostnames",
            "syntax_check": False,
            "groups": {
                "g": {"conditions": {"role": "router"}, "template": "rule;"},
            },
        }
        result = generate_syslog_config([make_device(role="switch")], cfg)
        assert result is False
        assert not (tmp_path / "syslog.conf").exists()

    def test_no_matching_devices_removes_existing_file(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"
        config_file.write_text("old content")

        cfg = {
            "config_file": str(config_file),
            "block_name": "fix_hostnames",
            "syntax_check": False,
            "groups": {
                "g": {"conditions": {"role": "router"}, "template": "rule;"},
            },
        }
        result = generate_syslog_config([make_device(role="switch")], cfg)
        assert result is True
        assert not config_file.exists()

    def test_writes_new_config(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"
        cfg = {
            "config_file": str(config_file),
            "block_name": "fix_hostnames",
            "syntax_check": False,
            "groups": {
                "g": {
                    "conditions": {},
                    "host_field": "main_ip",
                    "template": 'set("{name}" value(".Host") source-ip("{ip}"));',
                },
            },
        }
        devices = [
            make_device(name="rtr1", main_ip="10.0.0.1"),
            make_device(name="rtr2", main_ip="10.0.0.2"),
        ]
        result = generate_syslog_config(devices, cfg)

        assert result is True
        content = config_file.read_text()
        assert "rtr1" in content
        assert "10.0.0.1" in content
        assert "rtr2" in content

    def test_unchanged_config_skips_write(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"
        cfg = {
            "config_file": str(config_file),
            "block_name": "fix_hostnames",
            "syntax_check": False,
            "groups": {
                "g": {
                    "conditions": {},
                    "host_field": "main_ip",
                    "template": 'set("{name}" value(".Host"));',
                },
            },
        }
        devices = [make_device(name="rtr1", main_ip="10.0.0.1")]

        # First write
        generate_syslog_config(devices, cfg)
        first_mtime = config_file.stat().st_mtime

        # Second run with same data
        import time

        time.sleep(0.05)
        result = generate_syslog_config(devices, cfg)

        assert result is False
        assert config_file.stat().st_mtime == first_mtime

    def test_skips_devices_without_ip(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"
        cfg = {
            "config_file": str(config_file),
            "block_name": "fix_hostnames",
            "syntax_check": False,
            "groups": {
                "g": {
                    "conditions": {},
                    "host_field": "main_ip",
                    "template": 'set("{name}" value(".Host"));',
                },
            },
        }
        devices = [make_device(name="rtr1", main_ip=None)]
        result = generate_syslog_config(devices, cfg)

        assert result is False
        assert not config_file.exists()

    def test_skips_devices_without_name(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"
        cfg = {
            "config_file": str(config_file),
            "syntax_check": False,
            "groups": {
                "g": {
                    "conditions": {},
                    "host_field": "main_ip",
                    "template": 'set("{name}" value(".Host"));',
                },
            },
        }
        devices = [make_device(name=None, main_ip="10.0.0.1")]
        result = generate_syslog_config(devices, cfg)
        assert result is False

    def test_name_quote_escaping(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"
        cfg = {
            "config_file": str(config_file),
            "syntax_check": False,
            "groups": {
                "g": {
                    "conditions": {},
                    "host_field": "main_ip",
                    "template": 'set("{name}" value(".Host"));',
                },
            },
        }
        devices = [make_device(name='device"in"quotes', main_ip="10.0.0.1")]
        generate_syslog_config(devices, cfg)

        content = config_file.read_text()
        assert '\\"' in content


# ---------------------------------------------------------------------------
# _check_syntax
# ---------------------------------------------------------------------------


class TestCheckSyntax:
    def test_binary_not_found_returns_true(self) -> None:
        with patch("netbox2prom.generators.syslog.shutil.which", return_value=None):
            ok, error = _check_syntax("/fake/path")
            assert ok is True
            assert error == ""


# ---------------------------------------------------------------------------
# reload_syslog
# ---------------------------------------------------------------------------


class TestReloadSyslog:
    def test_no_ctl_binary_skips_gracefully(self) -> None:
        with patch("netbox2prom.generators.syslog.shutil.which", return_value=None):
            reload_syslog({"config_file": "/tmp/test.conf"})
            # No exception raised is the assertion

    def test_reload_success_and_health_check_running(self, tmp_path) -> None:
        """Full reload flow: reload OK, health check says 'running' → bak removed."""
        config_file = tmp_path / "syslog.conf"
        bak_file = tmp_path / "syslog.conf.bak"
        config_file.write_text("content")
        bak_file.write_text("backup")

        run_count = 0

        def fake_run_ctl(cmd, log_errors=True):
            nonlocal run_count
            run_count += 1
            if run_count == 1:
                return "Reloaded"
            return "syslog-ng is running"

        with (
            patch(
                "netbox2prom.generators.syslog.shutil.which", return_value="/usr/sbin/syslog-ng-ctl"
            ),
            patch("netbox2prom.generators.syslog.time.sleep"),
            patch("netbox2prom.generators.syslog._run_ctl", side_effect=fake_run_ctl),
            patch("netbox2prom.generators.syslog._remove_safely") as mock_remove,
        ):
            reload_syslog({"config_file": str(config_file), "health_check_delay": 0})
            mock_remove.assert_called_once_with(str(bak_file))

    def test_reload_health_check_not_running_triggers_rollback(self, tmp_path) -> None:
        """When syslog-ng is not running after reload, rollback is attempted."""
        config_file = tmp_path / "syslog.conf"
        bak_file = tmp_path / "syslog.conf.bak"
        config_file.write_text("new")
        bak_file.write_text("old")

        run_count = 0

        def fake_run_ctl(cmd, log_errors=True):
            nonlocal run_count
            run_count += 1
            if run_count == 1:
                return "ok"
            return "stopped"  # not running

        with (
            patch(
                "netbox2prom.generators.syslog.shutil.which", return_value="/usr/sbin/syslog-ng-ctl"
            ),
            patch("netbox2prom.generators.syslog.time.sleep"),
            patch("netbox2prom.generators.syslog._run_ctl", side_effect=fake_run_ctl),
            patch("netbox2prom.generators.syslog._rollback") as mock_rollback,
        ):
            reload_syslog({"config_file": str(config_file), "health_check_delay": 0})
            mock_rollback.assert_called_once()

    def test_reload_cmd_fails_skips_health_check(self, tmp_path) -> None:
        config_file = tmp_path / "syslog.conf"

        with (
            patch(
                "netbox2prom.generators.syslog.shutil.which", return_value="/usr/sbin/syslog-ng-ctl"
            ),
            patch("netbox2prom.generators.syslog._run_ctl", return_value=None),
            patch("netbox2prom.generators.syslog.time.sleep") as mock_sleep,
        ):
            reload_syslog({"config_file": str(config_file)})
            mock_sleep.assert_not_called()


# ---------------------------------------------------------------------------
# _run_ctl
# ---------------------------------------------------------------------------


class TestRunCtl:
    def test_successful_command(self) -> None:
        mock_result = MagicMock()
        mock_result.returncode = 0
        mock_result.stdout = "ok\n"
        mock_result.stderr = ""

        with patch("netbox2prom.generators.syslog.subprocess.run", return_value=mock_result):
            assert _run_ctl(["echo", "hi"]) == "ok"

    def test_failed_command_returns_none(self) -> None:
        mock_result = MagicMock()
        mock_result.returncode = 1
        mock_result.stdout = ""
        mock_result.stderr = "error"

        with patch("netbox2prom.generators.syslog.subprocess.run", return_value=mock_result):
            assert _run_ctl(["bad"]) is None

    def test_timeout_returns_none(self) -> None:
        with patch(
            "netbox2prom.generators.syslog.subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd="x", timeout=15),
        ):
            assert _run_ctl(["slow"]) is None

    def test_filenotfound_returns_none(self) -> None:
        with patch(
            "netbox2prom.generators.syslog.subprocess.run",
            side_effect=FileNotFoundError("not found"),
        ):
            assert _run_ctl(["missing"]) is None


# ---------------------------------------------------------------------------
# _remove_safely
# ---------------------------------------------------------------------------


class TestRemoveSafely:
    def test_removes_existing_file(self, tmp_path) -> None:
        f = tmp_path / "test.txt"
        f.write_text("data")
        _remove_safely(str(f))
        assert not f.exists()

    def test_missing_file_no_error(self) -> None:
        _remove_safely("/nonexistent/file/path")

    def test_permission_error_no_raise(self) -> None:
        with patch("netbox2prom.generators.syslog.os.remove", side_effect=OSError("denied")):
            _remove_safely("/some/file")
