from __future__ import annotations

import logging
import os
import shutil
import subprocess
import tempfile
import time

from ..conditions import match_conditions
from ..models import Device

logger = logging.getLogger(__name__)

_HEADER = (
    "# Generated by netbox2prom - do not edit manually.\n"
    "# This file is fully managed and will be overwritten on the next run.\n"
)


def generate_syslog_config(devices: list[Device], syslog_config: dict) -> bool:
    config_file = syslog_config.get("config_file")
    block_name = syslog_config.get("block_name", "fix_hostnames")
    groups = syslog_config.get("groups", {})
    epilogue_template = syslog_config.get("epilogue_template", "")
    syntax_check = syslog_config.get("syntax_check", True)

    if not config_file:
        logger.error("syslog config_file not configured")
        return False

    rules: list[str] = []
    for group_name, gcfg in groups.items():
        conditions = gcfg.get("conditions", {})
        host_field = gcfg.get("host_field", "main_ip")
        template = gcfg.get("template", "")

        for dev in devices:
            if not match_conditions(dev, conditions):
                continue
            ip = getattr(dev, host_field, None)
            if not ip or not dev.name:
                continue
            name_clean = dev.name.strip().replace('"', '\\"')
            rules.append(template.format(name=name_clean, ip=ip))
            logger.debug("Syslog [%s]: Added rule for %s", group_name, dev.name)

    if not rules:
        logger.info("No devices matched syslog rules")
        if os.path.exists(config_file):
            _remove_safely(config_file)
            return True
        return False

    content = _build_content(block_name, rules, epilogue_template)

    valid, error = _validate_structure(content, block_name)
    if not valid:
        logger.error("Structural validation failed: %s", error)
        return False

    try:
        with open(config_file, "r", encoding="utf-8") as f:
            existing = f.read()
        if existing == content:
            logger.debug("Syslog config unchanged, skipping write")
            return False
    except FileNotFoundError:
        existing = None

    directory = os.path.dirname(config_file) or "."
    os.makedirs(directory, exist_ok=True)

    tmp_fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".netbox2prom_", suffix=".tmp")
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.chmod(tmp_path, 0o644)

        if syntax_check:
            ok, syntax_error = _check_syntax(tmp_path)
            if not ok:
                logger.error("syslog-ng syntax check failed: %s", syntax_error)
                os.remove(tmp_path)
                return False

        if existing is not None:
            shutil.copy2(config_file, config_file + ".bak")

        os.replace(tmp_path, config_file)
        logger.info("Written %d rule(s) to %s", len(rules), config_file)
    except Exception:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise

    return True


def reload_syslog(syslog_config: dict) -> None:
    control_socket = syslog_config.get("control_socket", "/var/lib/syslog-ng/syslog-ng.ctl")
    config_file = syslog_config.get("config_file", "")
    health_check_delay = int(syslog_config.get("health_check_delay", 3))

    ctl = shutil.which("syslog-ng-ctl")
    if not ctl:
        logger.warning("syslog-ng-ctl not found in PATH, skipping reload")
        return

    reload_cmd = [ctl, "reload", f"--control={control_socket}"]
    status_cmd = [ctl, "status", f"--control={control_socket}"]

    output = _run_ctl(reload_cmd)
    if output is None:
        logger.warning("syslog-ng reload command failed, skipping health check")
        return
    logger.info("syslog-ng config reloaded successfully")

    time.sleep(health_check_delay)

    status = _run_ctl(status_cmd, log_errors=False)
    if status is not None and "running" in status.lower():
        logger.debug("syslog-ng health check: running")
        _remove_safely(config_file + ".bak")
    else:
        logger.critical("syslog-ng is NOT running after reload, attempting rollback...")
        _rollback(config_file, reload_cmd)


def _build_content(block_name: str, rules: list[str], epilogue_template: str) -> str:
    parts = [_HEADER, f"rewrite {block_name} {{\n"]
    parts.append("\n".join(rules))
    if epilogue_template:
        parts.append("\n" + epilogue_template.format())
    parts.append("\n};\n")
    return "".join(parts)


def _validate_structure(content: str, block_name: str) -> tuple[bool, str]:
    code_lines = []
    for line in content.split("\n"):
        if line.strip().startswith("#"):
            continue
        code_lines.append(line)
    code = "\n".join(code_lines).strip()

    expected_start = f"rewrite {block_name} {{"
    if not code.startswith(expected_start):
        return False, f"Expected block to start with 'rewrite {block_name} {{{{'"

    if not code.rstrip().endswith("};"):
        return False, "Expected block to end with '};'"

    brace_count = 0
    in_string = False
    escape = False
    for ch in code:
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            brace_count += 1
        elif ch == "}":
            brace_count -= 1
            if brace_count < 0:
                return False, "Unmatched closing brace"

    if brace_count != 0:
        return False, f"Unbalanced braces (count={brace_count})"

    return True, ""


def _check_syntax(filepath: str) -> tuple[bool, str]:
    binary = shutil.which("syslog-ng")
    if not binary:
        logger.debug("syslog-ng binary not found, skipping syntax check")
        return True, ""

    try:
        result = subprocess.run(
            [binary, "--syntax-only", f"--cfgfile={filepath}"],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode == 0:
            logger.debug("syslog-ng syntax check passed")
            return True, ""
        msg = result.stderr.strip() or result.stdout.strip()
        return False, msg
    except subprocess.TimeoutExpired:
        return False, "syslog-ng syntax check timed out"
    except Exception as e:
        logger.debug("Could not run syslog-ng syntax check: %s", e)
        return True, ""


def _run_ctl(cmd: list[str], log_errors: bool = True) -> str | None:
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
    except subprocess.TimeoutExpired:
        if log_errors:
            logger.error("syslog-ng-ctl command timed out: %s", " ".join(cmd))
        return None
    except FileNotFoundError:
        if log_errors:
            logger.error("syslog-ng-ctl not found")
        return None

    if result.returncode != 0:
        msg = result.stderr.strip() or result.stdout.strip()
        if log_errors:
            logger.error("syslog-ng-ctl failed: %s", msg)
        return None
    return result.stdout.strip()


def _rollback(config_file: str, reload_cmd: list[str]) -> None:
    backup = config_file + ".bak"
    if os.path.exists(backup):
        shutil.copy2(backup, config_file)
        subprocess.run(reload_cmd, capture_output=True, text=True, timeout=15)
        logger.critical("Rolled back to previous syslog-ng config from %s", backup)
    else:
        logger.critical("No backup available for rollback (%s)", backup)


def _remove_safely(filepath: str) -> None:
    try:
        os.remove(filepath)
        logger.debug("Removed %s", filepath)
    except FileNotFoundError:
        pass
    except OSError as e:
        logger.warning("Could not remove %s: %s", filepath, e)
